language: node_js
node_js:
  - "node"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: master
    env:
      - secure: zOJkRvDFHM4x05TYdysNR5wuurys3OawJrtYeMqtHbygTfP42IXp7axjEBYSR8I+Q/lmnPmHe7yZMamrjoz8YEYNQInccjyhRl/TV+IKdqvpRk8xCKnbY80kiTmL5p5DB6garNMpbclG1AdfDRCpmWsXF6AqbApbV2AVkPaNqPLnX0JPTft7v6Z+ZKRPbGU/wA/cM6GDfs8SSeC99jCYCysFb5kRsQpvTYCMLZ5SVb3TgpmPzU8cUJCCEPxysOcjk1Or7gupQ7VLe2Cwqo64npmhTsc5wRU45RD6eaIxxGhgaxgcumbGqYerae5QnCYR2jAAy35Qjx1eoCs2vM9IrAVUqoufv+AABgudwqOOhQLnMyLP9bzJZj03NY9VwtZzX9MF2/WVFWtUTPFGLLQsG0MVpDa+OvN/xdJd1PWwxSHobya9bvsK1jDZC3sCn5nOZDHxZl9zdXqTzTwDq4hqPNVkSXPuM/uQhwMS3a1K4mWtnZTmFxZZGlph9dFRy7Rh0IO0HWPjb/xmiEkRWxHBGD8zj5SPwHKO0IzHD0zDdVo/vCbhf3N/xvElKIVGU9SY8GVICx0v+6ojaYJtC+jdh84m61gIAXttiR/h94lwhIfdGgS6kyx8GyGF41oZ0fzm/gcY2O86f6Ro8pujgbcMt5JWkJeiCfu2sCgQQTren9E=
